Repository ComPlat/chemotion_ELN, pull requests merged in 2025-02, with the labels that each got.

#2214 feat: import samples additional attributes
  app/api/helpers/report_helpers.rb
  app/javascript/src/components/contextActions/ModalExport.js
  lib/export/export_chemicals.rb
  lib/export/export_excel.rb
  lib/export/export_sdf.rb
  lib/export/export_table.rb
  lib/import/import_chemicals.rb
  lib/import/import_samples.rb
  lib/import/import_sdf.rb
  spec/api/chemotion/sample_api_spec.rb
  spec/lib/export/export_chemicals_spec.rb
  spec/lib/export/export_excel_spec.rb
  spec/lib/import/import_chemicals_spec.rb
  spec/lib/import/import_samples_spec.rb
  spec/lib/import/import_sdf_spec.rb
Labels: enhancement

#2255 fix: creating molecules with invalid molfile using faulty smiles
  app/api/chemotion/molecule_api.rb
  lib/pub_chem.rb
  spec/api/molecule_api_spec.rb
  spec/fixtures/structures/bad_smiles.json
  spec/fixtures/structures/invalid_01.mol
  spec/models/molecule_spec.rb
  spec/spec_helper.rb
Labels: bug

#2324 fix(UI): adjust css for scrollbar and hidden dropdown
  app/javascript/src/components/navigation/UserAuth.js
  app/javascript/src/components/navigation/search/AutoCompleteInput.js
Labels: bug

#2250 feat: Incorporate "Gas Scheme" feature in reaction variations table
  CHANGELOG.md
  app/api/entities/reaction_variation_entity.rb
  app/javascript/src/apps/mydb/elements/details/reactions/ReactionDetails.js
  app/javascript/src/apps/mydb/elements/details/reactions/variationsTab/ReactionVariations.js
  app/javascript/src/apps/mydb/elements/details/reactions/variationsTab/ReactionVariationsAnalyses.js
  app/javascript/src/apps/mydb/elements/details/reactions/variationsTab/ReactionVariationsCellComponents.js
  app/javascript/src/apps/mydb/elements/details/reactions/variationsTab/ReactionVariationsComponents.js
  app/javascript/src/apps/mydb/elements/details/reactions/variationsTab/ReactionVariationsMaterials.js
  app/javascript/src/apps/mydb/elements/details/reactions/variationsTab/ReactionVariationsReducers.js
  app/javascript/src/apps/mydb/elements/details/reactions/variationsTab/ReactionVariationsUtils.js
  app/javascript/src/models/Reaction.js
  db/migrate/20241129093956_add_gas_materials_to_reaction_variations.rb
  lib/reporter/docx/detail_reaction.rb
  spec/api/entities/reaction_entity_spec.rb
  spec/factories/reactions.rb
  spec/javascripts/helper/reactionVariationsHelpers.js
  spec/javascripts/packs/src/apps/mydb/elements/details/reactions/variationsTab/ReactionVariationsCellComponents.spec.js
  spec/javascripts/packs/src/apps/mydb/elements/details/reactions/variationsTab/ReactionVariationsComponents.spec.js
  spec/javascripts/packs/src/apps/mydb/elements/details/reactions/variationsTab/ReactionVariationsMaterials.spec.js
  spec/javascripts/packs/src/apps/mydb/elements/details/reactions/variationsTab/ReactionVariationsUtils.spec.js
Labels: enhancement, feature
